## Import the Libraries

In [2]:
from sklearn import svm
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import classification_report

## Import the Dataset 

In [3]:
data = load_iris()
X=data['data']
y=data['target']

## Exploring the Dataset 

In [18]:
print(X[:10])


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [19]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


## Splitting the Dataset 

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

## Model Implementation and Fitting

In [12]:
supportvectormachine = svm.SVC(gamma='auto')
supportvectormachine.fit(X_train,y_train)
supportvectormachine

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

## Model Prediction

In [13]:
predictions = supportvectormachine.predict(X_test)
predictions

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2])

## Support Vectors

In [14]:
supportvectormachine.support_vectors_

array([[4.3, 3. , 1.1, 0.1],
       [5.7, 4.4, 1.5, 0.4],
       [4.5, 2.3, 1.3, 0.3],
       [5.1, 3.3, 1.7, 0.5],
       [5. , 2. , 3.5, 1. ],
       [6.3, 3.3, 4.7, 1.6],
       [7. , 3.2, 4.7, 1.4],
       [6. , 3.4, 4.5, 1.6],
       [6.1, 3. , 4.6, 1.4],
       [6.9, 3.1, 4.9, 1.5],
       [5.1, 2.5, 3. , 1.1],
       [6.2, 2.2, 4.5, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [4.9, 2.4, 3.3, 1. ],
       [6.3, 2.5, 4.9, 1.5],
       [6.7, 3. , 5. , 1.7],
       [5.9, 3.2, 4.8, 1.8],
       [6.3, 2.3, 4.4, 1.3],
       [6.9, 3.1, 5.1, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.3, 2.7, 4.9, 1.8],
       [6.3, 2.8, 5.1, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [5.9, 3. , 5.1, 1.8],
       [6.5, 3.2, 5.1, 2. ],
       [7.2, 3. , 5.8, 1.6],
       [7.7, 2.6, 6.9, 2.3],
       [7.9, 3.8, 6.4, 2. ],
       [6. , 3. , 4.8, 1.8],
       [6.3, 3.4, 5.6, 2.4],
       [5.8, 2.7, 5.1, 1.9],
       [7.7, 3.8, 6.7, 2.2]])

## Support Vector Indices 

In [15]:
supportvectormachine.support_

array([ 31,  35,  53,  73,   7,  14,  20,  22,  28,  36,  39,  41,  70,
        77,  94,  95, 103, 104,   4,  10,  16,  17,  18,  19,  21,  38,
        51,  60,  76,  78,  81,  88,  99, 110], dtype=int32)

## Number of Support Vectors for each Class

In [16]:
supportvectormachine.n_support_

array([ 4, 14, 16], dtype=int32)